#http://beyondvalence.blogspot.in/2014/02/r-partial-least-squares-regression.html
set.seed (1220104)
library(pls)
library(MASS)
library(caret)
library(bootstrap)
library(leaps)
library(car)
library (ggplot2)
library (plspm)
check <- read.csv (file = "caco_train_desc_top11", header=TRUE, sep = ",")
# check1 <- as.numeric (as.character(check$Factor))
train <- check[2:13]
train1 <- plsr(logPapp ~ NumHAcceptors+HeavyAtomCount+SlogP_VSA9+LabuteASA+NHOHCount+PEOE_VSA9+VSA_EState8+NumHDonors+EState_VSA1+SlogP_VSA12+TPSA, data = train, validation = "LOO")
summary(train1)

#plot(RMSEP(train1), legendpos = "topright")
#plot(train1, ylim=c(-7,-3), xlim=c(-7,-3), asp = 1, line = TRUE, ncomp=4)
#plot(train1, plottype = "scores", comps = 1:3)
explvar(train1)
#plot(train1, "loadings", comps = 1:2, legendpos = "topleft", xlab = "nm")
check1 <- read.csv (file = "caco_test_desc_top11", header=TRUE, sep = ",")
train2 <- check1[2:12]
y<- check1[,13]
#predict(train1+ newdata = train2)
pls.pred2<-predict(train1, train2, ncomp=4)
pls.eval<-data.frame(obs=y, pred=pls.pred2[,1,1])
write.table (pls.eval, file = "eval_table", sep = "\t")
correlation_accuracy <- cor(pls.eval)
r2<-defaultSummary(pls.eval)
write.table (correlation_accuracy, file = "CoAcc", sep = "\t")
plot(y, pls.pred2, ylim=c(-7,-3), xlim=c(-7,-3), main="Observed and PLS predicted logPapp", xlab = "exp value", ylab = "PLS Predicted")
abline(0,1, col="red")
legend("topleft", bty="n", text.col= "red", legend=paste("R^2 :", format(r2[2], digits=3)))
